name: Build Packer AMI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packer/**"

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Packer
        uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232 # v3.1.0

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Packer AMI
        run: |
          cd packer
          packer fmt .
          packer init .
          packer validate build.pkr.hcl
          packer build build.pkr.hcl

  slack-notify:
    needs:
      - build
    if: always()
    runs-on: ubuntu-latest
    steps:
       - name: Slack notification
         uses: come25136/workflow-notification-for-slack@main
         with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
